DECLARE
	/*DECLARAÇÃO DAS VARIAVEIS*/
	v_codigo EMPREGADO.CODIGO%TYPE;
	v_hora50 EMPREGADO.HORA50%TYPE;
	v_hora100 EMPREGADO.HORA100%TYPE;
	v_valor EMPREGADO.SALARIO%TYPE;
	v_total EMPREGADO.SALARIO%TYPE;
	v_salario EMPREGADO.SALARIO%TYPE;
	v_tipo CHAR(4);
	v_jornada EMPREGADO.JORNADA%TYPE;

	/*DECLARAÇÃO~E PREENCHIMENTO DO CURSO*/
	CURSOR HORAS_EXTRAS IS
		SELECT CODIGO, SALARIO, HORA50, HORA100, JORNADA
		FROM EMPREGADO;

	/*COMEÇAR O BLOCO*/
	BEGIN
		DELETE FROM HORA_EXTRA;
		OPEN HORAS_EXTRAS;
		LOOP
			/*PREENCHENDO AS VARIAVEIS COM O VALOR DO CURSOR*/
			FETCH HORAS_EXTRAS INTO v_codigo, v_salario, v_hora50, v_hora100, v_jornada;
			EXIT WHEN HORAS_EXTRAS%NOTFOUND;

			/*CALCULO HORA 50*/
			v_total := ((v_salario/v_jornada)*1.5)*v_hora50;
			INSERT INTO HORA_EXTRA VALUES (v_codigo, v_hora50, v_total,'50');

			/*CALCULO HORA 100*/
			v_total := ((v_salario/v_jornada)*2.0)*v_hora100;
			INSERT INTO HORA_EXTRA VALUES (v_codigo, v_hora100, v_total,'100');

		END LOOP;
		CLOSE HORAS_EXTRAS;
	END;